### PR TITLE
Fixes #110 & introduces condense formatting option

### LINKED ISSUE #110: Formatter deletes comments and all whitespace on save
The problem is that if your graphviz file looks like this and you save it:
```dot
strict digraph {
  /* This block comment is important or something. */

  // I want to remember this later....
  // layout = "dot";
  node [
    fillcolor = "#ffffff",
  ];

  // general note related to nothing important

  // cool info here about this connection
  "hello" -> "graph";
}
```

Gets transformed into this:
```dot
strict digraph {
  node [
    fillcolor = "#ffffff",
  ];
  // cool info here about this connection
  "hello" -> "graph";
}
```

The assertions being made by the formatter are really wild. 

Temporary solution for users is to just disable it.
- Open the command palette (`CTRL+Shift+P` or `Command+Shift+P`)
- Search for and open `Preferences: Open Settings (JSON)`
- Add the following in the settings and save (take note that there is a comma at the end of this snippet)
```json
    "[dot]": {
        "editor.formatOnSave": false
    },
```

### PR DESCRIPTION
**Pull request by bigbug**

### CODE REVIEW

**Comment by protosam** [comment]
Thanks so much for working on this. This is much closer to what I think would be expected.

When testing `condenseAttributes`, it seems to work with the graphs I've been working on.

If you take the original example and repeatedly run the formatter, you'll see some odd behavior occur.  Just spam the hotkey for it:
- `Shift + Alt + F` on Windows
- `Shift + Option + F` on Mac
- `Ctrl + Shift + I` on Linux

It continues to add a new line between comments and `node`.

What people would probably expect is like:
- comments before valid keywords/tokens should stay together
- multiple new lines would become a single new line

**Comment by bigbug** [comment]
> Thanks so much for working on this. This is much closer to what I think would be expected.
> 
> When testing `condenseAttributes`, it seems to work with the graphs I've been working on.
> 
> If you take the original example and repeatedly run the formatter, you'll see some odd behavior occur. Just spam the hotkey for it:
> 
> * `Shift + Alt + F` on Windows
> * `Shift + Option + F` on Mac
> * `Ctrl + Shift + I` on Linux
> 
> It continues to add a new line between comments and `node`.
> 
> What people would probably expect is like:
> 
> * comments before valid keywords/tokens should stay together
> * multiple new lines would become a single new line

Hmm, it seems I forgot to push the latest changes. I also saw this behaviour and fixed it already. Please check again.

**Comment by tintinweb** [comment]
Great work!

I've noticed that if you repeatedly run the formatted on example `36_large.dot` indentations will shift. Other than that works as described, preserves comments, better than what we had before 🥳

**Review by tintinweb — APPROVED** [review]

**Comment by bigbug** [comment]
> I've noticed that if you repeatedly run the formatted on example `36_large.dot` indentations will shift. Other than that works as described, preserves comments, better than what we had before 🥳

HTML indentation has been fixed

**Pull request merged**
