### PR TITLE
Fixes #11 (SVG export bug with HTML chars) - rebased off master

### LINKED ISSUE #11: svg export does not escape angle brackets in node labels
```
<g id="node16" class="node" data-name="load<Foo>(\nconst string &amp; key, bool bla)" data-comment="..the same again..">
-------------------------------------------^
```

### PR DESCRIPTION
**Pull request by tintinweb**
this is #58 with c6c542fecd41b271d0e6df40bca6a632f1348dc2 cherry-picked to latest master.

> Uses browser's built in XML Serializer instead of document.getElementById("graph").innerHTML
Code from: [https://stackoverflow.com/questions/23218174/how-do-i-save-export-an-svg-file-after-creating-an-svg-with-d3-js-ie-safari-an](https://stackoverflow.com/questions/23218174/how-do-i-save-export-an-svg-file-after-creating-an-svg-with-d3-js-ie-safari-an)

>Fixes #11

I verified that this is working but would appreciate if you could double-check @bigbug 🙌

### CODE REVIEW

**Comment by bigbug** [comment]
Verified it compared to my previous implementation. However I just saw that exporting zoomed/translated SVGs causes problems. Don't know yet whether this was also present in the current 0.0.13.

**Comment by tintinweb** [comment]
what has changed is that with this PR we are exporting the current (pot. zoomed/translated) image as seen in the preview while before we exported the unchanged initial rendering.

Is this what you're observing too?

(IIRC someone even requested to be able to export the current view - after zooming or with highlighting - as an image.)

**Comment by bigbug** [comment]
Just went back to the old version. It seems that we were always exporting the current view as seen in the preview. So I guess nothing has changed here.
The highlighting is exported as well.
So this PR really exports just the way as it has been. For the future we should probably think about how to export the default viewport.

**Review by bigbug — APPROVED** [review]
(y)

**Comment by tintinweb** [comment]
alternatively, users can always reset the view and export that instead. But yeah, distinguishing between exporting "everything" and "the current view" might be helpful as well.

**Comment by bigbug** [comment]
maybe not that easy. I think at one point I implemented to also reset the highlighted nodes when you click on the reset button. So for some people it might be impossible to highlight the nodes they want and then zoom out so that everything is properly exported. Possibly this behaviour has to be changed again (or we split it up in two buttons?).

**Pull request merged**
