### PR TITLE
More control of behavior; Various fixes; Support for: render-lock, debouncing, inter-render interval; More in-code docs

### PR DESCRIPTION
**Pull request by michkot**
Hi! I like your extension, but I needed to use it for real-time monitoring of always-changing dot-files. So I made some minimal modifications, so that the render locking and/or render min delay can be set via configuration.
I also tried to make the contributes section of package.json consistent with the extension name.

### CODE REVIEW

**Comment by michkot** [comment]
I added a bunch of new features including debouncing.
I also fixed the odd behavior of nodes popping on every re-render (due to the jquery.graphviz.svg shrink option default).
See details in commit messages.
Fixes #5

**Comment by michkot** [comment]
I added a bunch of new features including debouncing.
I also fixed the odd behavior of nodes popping on every re-render (due to the jquery.graphviz.svg shrink option default).
See details in commit messages.
fixes #5

**Comment by tintinweb** [comment]
This is great, thanks @michkot 🙌 

I'll try to get this out asap but have to update another extension that is calling the now renamed preview command.

**Comment by tintinweb** [comment]
published as v0.0.8. cheers.

**Comment by michkot** [comment]
@tintinweb I hope that the (improved) extension will help more ppl. And sorry for the (unintended) breaking change in https://github.com/ConsenSys/vscode-solidity-auditor, it just seemed better to make VSC contributions in-line with its published name (I guess there was some story of the extension publish name VS repository name).

**Comment by tintinweb** [comment]
@michkot you're work is much appreciated. No worries about the breaking change, I had this on my todo list for some time and it is better to break things now while the list of foreign extensions using this command is still low :)

thx & cheers,
tin

**Pull request merged**
